/**
 * Chargeur de contenu : Supabase si configuré, sinon fallback sur /data/*.json.
 * Toutes les fonctions sont async et exécutées côté serveur.
 */

import articlesData from "@/../data/articles.json";
import eventsData from "@/../data/events.json";
import announcementsData from "@/../data/announcements.json";
import restaurantsData from "@/../data/restaurants.json";
import activitiesData from "@/../data/activities.json";
import infoData from "@/../data/info-pratiques.json";

import type {
  Article,
  Event,
  Announcement,
  Restaurant,
  Activity,
  InfoPratique,
} from "@/lib/content-types";

import {
  dbListArticles,
  dbGetArticleBySlug,
  dbListEvents,
  dbListAnnouncements,
  dbListRestaurants,
  dbListActivities,
  dbListInfoPratiques,
} from "@/lib/supabase/queries";
import {
  mergeInfoPratiqueCatalog,
  normalizeInfoTitle,
} from "@/lib/info-catalog";
import { isClosedRestaurant } from "@/lib/closed-restaurants";
import { isStaleFacebookEvent } from "@/lib/facebook-event-filters";
import {
  isAnnouncementVisible,
} from "@/lib/announcement-expiry";
import { catalogOpeningHoursForRestaurant } from "@/lib/restaurant-catalog";
import { enrichRestaurantsWithHours } from "@/lib/restaurant-hours";
import type { RestaurantOpenMeta } from "@/lib/restaurant-open-status";

import type {
  ArticleRow,
  EventRow,
  AnnouncementRow,
  RestaurantRow,
  ActivityRow,
  InfoRow,
} from "@/lib/supabase/types";
import { normalizeTitleKey } from "@/lib/cover-image";
import { dedupeArticlesForDisplay } from "@/lib/article-dedupe";
import {
  normalizeAnnouncementType,
  normalizeArticleCategory,
  normalizeEventCategory,
} from "@/lib/content-labels";
import { parseCarpoolBody, type ParsedCarpoolOffer } from "@/lib/covoiturage";
import { getCarpoolSignupCounts } from "@/lib/carpool-signups";
import {
  isFacebookAutoGeneratedPlaceholder,
} from "@/lib/facebook-import-filters";
import { isFacebookCdnCoverUrl } from "@/lib/facebook-cover-persist";
import { resolveGardePosterPublicUrl } from "@/lib/garde-poster-url";
import { SITE } from "@/lib/constants";

// =====================================================================
// Articles
// =====================================================================

export async function getArticles(): Promise<Article[]> {
  const db = await dbListArticles();
  if (db) {
    return dedupeArticlesForDisplay(
      db
        .map(articleFromRow)
        .filter((a) => !shouldHideEmptyFacebookShell(a)),
    );
  }
  return (articlesData as Article[])
    .slice()
    .sort(
      (a, b) =>
        new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    );
}

export async function getFeaturedArticles(): Promise<Article[]> {
  const all = await getArticles();
  return all.filter((a) => a.featured);
}

export async function getArticleBySlug(
  slug: string
): Promise<Article | undefined> {
  const db = await dbGetArticleBySlug(slug);
  if (db) {
    const article = articleFromRow(db);
    if (
      slug.startsWith("mooreanews-fb-") &&
      !hasPersistedCoverUrl(article.image)
    ) {
      article.image = `/api/facebook-cover?slug=${encodeURIComponent(slug)}`;
    }
    return article;
  }
  return (articlesData as Article[]).find((a) => a.slug === slug);
}

// =====================================================================
// Events
// =====================================================================

export async function getEvents(): Promise<Event[]> {
  const db = await dbListEvents();
  if (db) {
    return db
      .filter((r) => !isStaleFacebookEvent(r))
      .map(eventFromRow);
  }
  return (eventsData as Event[])
    .slice()
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

export async function getUpcomingEvents(limit?: number): Promise<Event[]> {
  const today = new Date().toISOString().slice(0, 10);
  const all = await getEvents();
  const items = all.filter((e) => e.date >= today);
  return typeof limit === "number" ? items.slice(0, limit) : items;
}

/** Événements dans une plage de dates (séjour visiteur). */
export async function getEventsBetween(
  startDate: string,
  endDate: string,
): Promise<Event[]> {
  const all = await getEvents();
  return all.filter((e) => e.date >= startDate && e.date <= endDate);
}

export async function getEventBySlug(
  slug: string,
): Promise<Event | undefined> {
  const all = await getEvents();
  return all.find((e) => e.slug === slug);
}

// =====================================================================
// Announcements
// =====================================================================

export async function getAnnouncements(): Promise<Announcement[]> {
  const db = await dbListAnnouncements();
  const raw = db
    ? db
        .filter((r) => r.category !== "covoiturage")
        .filter(isAnnouncementVisible)
        .map(announcementFromRow)
    : (announcementsData as Announcement[]).filter((a) =>
        isAnnouncementVisible({ created_at: a.publishedAt, expires_at: null }),
      );
  return raw.slice().sort((a, b) => {
    const aBoost = a.boosted ? 1 : 0;
    const bBoost = b.boosted ? 1 : 0;
    if (aBoost !== bBoost) return bBoost - aBoost;
    return (
      new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    );
  });
}

export async function getAnnouncementBySlug(
  slug: string,
): Promise<Announcement | undefined> {
  const all = await getAnnouncements();
  return all.find((a) => a.slug === slug);
}

export async function getCarpoolOffers(): Promise<ParsedCarpoolOffer[]> {
  const db = await dbListAnnouncements();
  if (!db) return [];

  const rows = db.filter(
    (r) => r.category === "covoiturage" && isAnnouncementVisible(r),
  );
  const signupCounts = await getCarpoolSignupCounts(rows.map((r) => r.id));

  return rows
    .map((row) => {
      const parsed = parseCarpoolBody(row.body);
      const seats = parsed.seats ?? 1;
      const signupCount = signupCounts[row.id] ?? 0;
      return {
        id: row.id,
        title: row.title,
        publishedAt: row.created_at,
        contact: row.contact ?? "",
        phone: row.contact ?? "",
        author: row.author ?? "",
        direction: parsed.direction ?? "vers-quai",
        tripDate: parsed.tripDate ?? "",
        time: parsed.time ?? "",
        tripDays: parsed.tripDays,
        seats,
        signupCount,
        seatsLeft: Math.max(0, seats - signupCount),
        meetingPoint: parsed.meetingPoint ?? row.district ?? "",
        destination: parsed.destination ?? "",
        priceShare: parsed.priceShare,
        notes: undefined,
      };
    })
    .sort((a, b) => {
      const byDate = a.tripDate.localeCompare(b.tripDate);
      if (byDate !== 0) return byDate;
      return a.time.localeCompare(b.time);
    });
}

// =====================================================================
// Restaurants
// =====================================================================

export async function getRestaurants(): Promise<Restaurant[]> {
  const db = await dbListRestaurants();
  const list = db
    ? db.map(restaurantFromRow)
    : (restaurantsData as Restaurant[]);
  const open = list.filter((r) => !isClosedRestaurant(r));
  return enrichRestaurantsWithHours(open);
}

export async function getRestaurantBySlug(
  slug: string,
): Promise<Restaurant | undefined> {
  const db = await dbListRestaurants();
  if (db) {
    const row = db.find((r) => r.id === slug);
    if (row && !isClosedRestaurant({ name: row.name, slug: row.id })) {
      const [enriched] = await enrichRestaurantsWithHours([restaurantFromRow(row)]);
      return enriched;
    }
    return undefined;
  }
  const fromJson = (restaurantsData as Restaurant[]).find((r) => r.slug === slug);
  if (!fromJson || isClosedRestaurant(fromJson)) return undefined;
  const [enriched] = await enrichRestaurantsWithHours([fromJson]);
  return enriched;
}

// =====================================================================
// Activities
// =====================================================================

export async function getActivities(): Promise<Activity[]> {
  const db = await dbListActivities();
  if (db) return db.map(activityFromRow);
  return activitiesData as Activity[];
}

export async function getActivityBySlug(
  slug: string,
): Promise<Activity | undefined> {
  const all = await getActivities();
  return all.find((a) => a.slug === slug);
}

// =====================================================================
// Infos pratiques
// =====================================================================

const INFO_CATEGORY_ORDER: Record<InfoPratique["category"], number> = {
  urgence: 0,
  sante: 1,
  transport: 2,
  administration: 3,
  education: 4,
  commerce: 5,
};

function sortInfoPratiques(items: InfoPratique[]): InfoPratique[] {
  return items.slice().sort((a, b) => {
    const cat =
      INFO_CATEGORY_ORDER[a.category] - INFO_CATEGORY_ORDER[b.category];
    if (cat !== 0) return cat;
    return a.title.localeCompare(b.title, "fr");
  });
}

/** Catalogue JSON toujours fusionné avec Supabase (slugs stables, ex. RAI TAHITI). */
export async function getInfoPratiques(): Promise<InfoPratique[]> {
  const json = infoData as InfoPratique[];
  const db = await dbListInfoPratiques();
  if (!db) return sortInfoPratiques(json);
  const dbItems = db.map(infoFromRow);
  return sortInfoPratiques(mergeInfoPratiqueCatalog(dbItems, json));
}

export async function getInfoPratiqueBySlug(
  slug: string,
): Promise<InfoPratique | undefined> {
  const jsonItem = (infoData as InfoPratique[]).find((i) => i.slug === slug);
  const all = await getInfoPratiques();
  const fromList = all.find((i) => i.slug === slug);
  if (fromList) return fromList;
  if (jsonItem) {
    const byTitle = all.find(
      (i) => normalizeInfoTitle(i.title) === normalizeInfoTitle(jsonItem.title),
    );
    return byTitle ?? jsonItem;
  }
  return undefined;
}

/** Slugs stables pour pré-génération (JSON + base). */
export async function getAllInfoPratiqueSlugs(): Promise<string[]> {
  const json = infoData as InfoPratique[];
  const all = await getInfoPratiques();
  return [...new Set([...json.map((i) => i.slug), ...all.map((i) => i.slug)])];
}

// =====================================================================
// Mapping Row (Supabase) → Type (front)
// =====================================================================

function hasPersistedCoverUrl(url: string | null | undefined): boolean {
  const u = url?.trim() ?? "";
  if (!u.startsWith("http")) return false;
  if (isFacebookCdnCoverUrl(u)) return false;
  return true;
}

/** Masque les coquilles Facebook vides (texte + affiche absents). */
function shouldHideEmptyFacebookShell(a: Article): boolean {
  if (!a.slug.startsWith("mooreanews-fb-")) return false;
  if (hasPersistedCoverUrl(a.image)) return false;
  return isFacebookAutoGeneratedPlaceholder({
    title: a.title,
    excerpt: a.excerpt ?? null,
    body: a.body,
  });
}

function articleFromRow(r: ArticleRow): Article {
  let image = r.cover_url ?? undefined;
  const isBrokenCover =
    !image?.trim() ||
    image.includes("fbcdn.net") ||
    image.includes("fbsbx.com");
  if (r.slug?.startsWith("garde-moorea-") && isBrokenCover) {
    const validFrom = r.slug.slice("garde-moorea-".length);
    image =
      resolveGardePosterPublicUrl(r.cover_url) ??
      `${SITE.url.replace(/\/$/, "")}/api/garde-weekend/poster/${validFrom}`;
  }
  // Pas de fallback /api/facebook-cover en liste — évite l’icône « image cassée ».
  return {
    slug: r.slug,
    title: r.title,
    excerpt: r.excerpt,
    body: r.body,
    category: normalizeArticleCategory(r.category),
    tags: r.tags ?? undefined,
    image,
    author: r.author ?? undefined,
    featured: r.featured,
    publishedAt: r.published_at,
  };
}

const ICPF_AFFICHE = "/images/events/depistage-cancer-peau-icpf-2026.jpg";

/** Affiches locales quand cover_url n’est pas encore en base (clé = titre normalisé). */
const EVENT_TITLE_COVERS: Record<string, string> = {
  "depistage de la peau": ICPF_AFFICHE,
};

function eventCoverFromRow(r: EventRow): string | undefined {
  const url = r.cover_url?.trim();
  if (url) return url;
  const key = normalizeTitleKey(r.title);
  if (EVENT_TITLE_COVERS[key]) return EVENT_TITLE_COVERS[key];
  if (key.includes("depistage") && key.includes("peau")) return ICPF_AFFICHE;
  return undefined;
}

function eventFromRow(r: EventRow): Event {
  return {
    slug: r.id,
    title: r.title,
    description: r.description,
    category: normalizeEventCategory(r.category),
    date: r.date,
    endDate: r.end_date ?? undefined,
    time: r.start_time ?? undefined,
    location: r.location,
    district: r.district ?? undefined,
    organizer: r.organizer ?? undefined,
    price: r.price ?? undefined,
    contact: r.contact ?? undefined,
    url: r.url ?? undefined,
    image: eventCoverFromRow(r),
  };
}

function announcementFromRow(r: AnnouncementRow): Announcement {
  const boosted =
    r.boosted_until != null && new Date(r.boosted_until).getTime() > Date.now();
  return {
    slug: r.id,
    title: r.title,
    body: r.body,
    type: normalizeAnnouncementType(r.category),
    district: r.district ?? undefined,
    price: r.price ?? undefined,
    contact: r.contact ?? "",
    publishedAt: r.created_at,
    image: r.cover_url ?? undefined,
    boosted,
  };
}

function restaurantFromRow(r: RestaurantRow): Restaurant {
  const premium = isPremiumRestaurant(r);
  return {
    slug: r.id,
    name: r.name,
    description: r.description,
    cuisine: r.cuisine,
    priceLevel: priceLevelFromRange(r.price_range),
    district: r.district,
    address: r.address,
    phone: r.phone ?? undefined,
    website: r.url ?? undefined,
    openingHours:
      catalogOpeningHoursForRestaurant(r.name, r.id) ||
      r.hours?.trim() ||
      undefined,
    image: r.cover_url ?? undefined,
    premium,
    lat: r.lat ?? undefined,
    lon: r.lon ?? undefined,
    googlePlaceId: r.google_place_id ?? undefined,
    merchantOpenStatus: r.merchant_open_status ?? undefined,
    merchantOpenUpdatedAt: r.merchant_open_updated_at ?? undefined,
    merchantEmail: r.merchant_email ?? undefined,
  };
}

function isPremiumRestaurant(r: RestaurantRow): boolean {
  if (r.featured) return true;
  if (!r.premium_until) return false;
  return new Date(r.premium_until).getTime() > Date.now();
}

export function restaurantToOpenMeta(r: Restaurant): RestaurantOpenMeta {
  return {
    slug: r.slug,
    name: r.name,
    district: r.district,
    googlePlaceId: r.googlePlaceId,
    merchantOpenStatus: r.merchantOpenStatus,
    merchantOpenUpdatedAt: r.merchantOpenUpdatedAt,
  };
}

function priceLevelFromRange(range: string | null): 1 | 2 | 3 | 4 {
  if (!range) return 2;
  const n = Number.parseInt(range, 10);
  if (n >= 1 && n <= 4) return n as 1 | 2 | 3 | 4;
  const symbols = (range.match(/€|\$/g) ?? []).length;
  return Math.min(4, Math.max(1, symbols || 2)) as 1 | 2 | 3 | 4;
}

function activityFromRow(r: ActivityRow): Activity {
  return {
    slug: r.id,
    name: r.name,
    description: r.description,
    category: r.category as Activity["category"],
    district: r.district ?? undefined,
    duration: r.duration ?? undefined,
    price: r.price ?? undefined,
    contact: r.phone ?? undefined,
    website: r.url ?? undefined,
    image: r.cover_url ?? undefined,
    lat: r.lat ?? undefined,
    lon: r.lon ?? undefined,
  };
}

function infoFromRow(r: InfoRow): InfoPratique {
  const jsonMatch = (infoData as InfoPratique[]).find(
    (j) => j.title.trim().toLowerCase() === r.title.trim().toLowerCase(),
  );
  return {
    slug: jsonMatch?.slug ?? r.id,
    title: r.title,
    description: r.description,
    category: r.category as InfoPratique["category"],
    address: r.address ?? undefined,
    phone: r.phone ?? undefined,
    hours: r.hours ?? undefined,
    website: r.url ?? undefined,
    image: jsonMatch?.image,
    lat: r.lat ?? jsonMatch?.lat,
    lon: r.lon ?? jsonMatch?.lon,
    mapIconUrl: r.map_icon_url ?? jsonMatch?.mapIconUrl,
  };
}
