/**
 * Import Facebook → Événement, Annonce ou Actualité (texte + affiche).
 */

import type { FacebookPostForImport } from "@/lib/facebook-article-import";
import type { FacebookPageImportConfig } from "@/lib/facebook-article-import";
import { getAdminSupabase } from "@/lib/supabase/admin";
import {
  isFacebookArticleNeedsRepair,
  isFacebookCoverMissingRepair,
  isFacebookCoverNeedsPersistOnly,
  isFacebookAutoGeneratedPlaceholder,
  isFacebookJunkText,
  isEmptyFacebookArticleShell,
  isRecentFacebookPost,
  facebookCronMaxRepairsPerRun,
  publishedAtFromFacebookPost,
  shouldImportFacebookPost,
} from "@/lib/facebook-import-filters";
import {
  enrichFacebookPostForImport,
  fetchGraphPostById,
  permalinkForPost,
} from "@/lib/facebook-post-enrich";
import {
  coverPersistUserMessage,
  coverUrlForDatabase,
  isFacebookCdnCoverUrl,
  persistFacebookCoverForPost,
  persistFacebookCoverUrl,
  repairPendingFbcdnCoversFromDb,
} from "@/lib/facebook-cover-persist";
import { hideExternalArticlesForArticleSlug } from "@/lib/facebook-external-sync";
import { isSlugImportBlocked } from "@/lib/import-blocklist";
import { unpublishEmptyFacebookShells } from "@/lib/facebook-import-cleanup";
import { cleanImportedText } from "@/lib/html-entities";
import { truncate } from "@/lib/utils";
import {
  announcementCategoryFromMessage,
  eventCategoryFromMessage,
  parseDateFromMessage,
  parseDistrictFromMessage,
  parseLocationFromMessage,
  parseTimeFromMessage,
  titleFromMessage,
  hasRelativeWeekdayDate,
} from "@/lib/facebook-post-parse";
import { humanEventTitle } from "@/lib/event-title";
import {
  tryImportFacebookAlert,
  tryImportFacebookMeteoAlert,
} from "@/lib/facebook-alert-import";
import { routeFacebookImport } from "@/lib/facebook-content-route";
import { facebookStoryIdFromPostId } from "@/lib/article-dedupe";
import { normalizeTitleKey } from "@/lib/cover-image";
import { isTransientSupabaseError } from "@/lib/feed-errors";

export type FacebookContentImportResult = {
  eventsCreated: number;
  announcementsCreated: number;
  articlesCreated: number;
  alertsCreated: number;
  skipped: number;
  skippedStale: number;
  errors: string[];
  createdEvents: { title: string; id: string; date: string }[];
  createdArticles: { title: string; slug: string }[];
  repairedArticles: { title: string; slug: string }[];
  createdAnnouncements: { title: string; id: string }[];
  createdAlerts: string[];
  articlesRepaired?: number;
  coversPersisted?: number;
  coversFailed?: number;
  warnings: string[];
};

function articleTelegramNotice(
  title: string,
  slug: string,
  excerpt?: string | null,
  body?: string,
): { title: string; slug: string } | null {
  if (
    isFacebookAutoGeneratedPlaceholder({
      title,
      excerpt: excerpt ?? null,
      body: body ?? "",
    })
  ) {
    return null;
  }
  return { title, slug };
}

function pushRepairedArticleNotice(
  result: FacebookContentImportResult,
  title: string,
  slug: string,
  excerpt?: string | null,
  body?: string,
): void {
  const notice = articleTelegramNotice(title, slug, excerpt, body);
  if (notice) result.repairedArticles.push(notice);
}

function pushImportFailure(
  result: FacebookContentImportResult,
  label: string,
  reason: string,
): void {
  const msg = `${label}: ${reason}`;
  if (isTransientSupabaseError(reason)) {
    result.warnings.push(msg);
  } else {
    result.errors.push(msg);
  }
}

/** Pages dont le fil est importé automatiquement (sans FACEBOOK_IMPORT_AS_ARTICLES). */
function isAutoImportFeedPage(config: FacebookPageImportConfig): boolean {
  return (
    Boolean(config.importAllFeedPosts) &&
    (config.pageKey === "mooreanews" || config.pageKey === "te-ito-rau")
  );
}

function importEnabled(config: FacebookPageImportConfig): boolean {
  if (isAutoImportFeedPage(config)) return true;
  return process.env.FACEBOOK_IMPORT_AS_ARTICLES === "true";
}

function eventsPublishedByDefault(): boolean {
  return process.env.FACEBOOK_EVENTS_PUBLISHED === "true";
}

/** Brouillon par défaut — publier seulement si FACEBOOK_ARTICLES_PUBLISHED=true sur Vercel. */
function publishedByDefault(): boolean {
  return process.env.FACEBOOK_ARTICLES_PUBLISHED === "true";
}

async function enrichPost(
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
): Promise<FacebookPostForImport> {
  const cleaned = {
    ...post,
    message: post.message ? cleanImportedText(post.message) : post.message,
  };
  if (!config.importAllFeedPosts) {
    return enrichFacebookPostForImport(cleaned, config.pageAccessToken, {
      pageId: config.graphPageId,
      importAll: false,
    });
  }
  return enrichFacebookPostForImport(cleaned, config.pageAccessToken, {
    pageId: config.graphPageId ?? "350029589936",
    importAll: true,
  });
}

function articleTitleFromPost(
  message: string,
  config: FacebookPageImportConfig,
  hasImage: boolean,
  publishedAt: string,
  imageCaption?: string,
): string {
  const clean = message.trim();
  const relaxed = Boolean(config.importAllFeedPosts);
  if (clean && (relaxed || !isFacebookJunkText(clean))) {
    const fromMsg = titleFromMessage(clean, "");
    if (fromMsg && (relaxed || !isFacebookJunkText(fromMsg))) return fromMsg;
    if (relaxed && clean.length >= 3) {
      return (
        fromMsg ||
        truncate(clean.split("\n")[0]?.trim() || clean.replace(/\s+/g, " "), 120)
      );
    }
  }
  const cap = imageCaption?.trim() ?? "";
  if (cap && !isFacebookJunkText(cap) && cap.length >= 8) {
    const fromCap = titleFromMessage(cap, "");
    if (fromCap && !isFacebookJunkText(fromCap)) return fromCap;
    return cap.slice(0, 120);
  }
  const timeLabel = tahitiTimeLabel(publishedAt);
  return hasImage
    ? `${config.pageName} — affiche · ${timeLabel}`
    : `${config.pageName} — publication · ${timeLabel}`;
}

function tahitiTimeLabel(iso: string): string {
  return new Date(iso).toLocaleString("fr-FR", {
    timeZone: "Pacific/Tahiti",
    day: "2-digit",
    month: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function slugForPost(pageKey: string, postId: string): string {
  const safe = postId.replace(/[^a-zA-Z0-9]/g, "-").slice(0, 80);
  return `${pageKey}-fb-${safe}`;
}

function graphPostIdFromMooreaNewsSlug(slug: string): string | null {
  const m = slug.match(/^mooreanews-fb-(\d+)-(\d{8,})$/);
  if (m) return `${m[1]}_${m[2]}`;
  const tail = slug.match(/(\d{10,})$/);
  if (tail) return `350029589936_${tail[1]}`;
  return null;
}

function facebookExcerpt(message: string, fallback: string): string {
  const flat = message.replace(/\n+/g, " ").replace(/\s+/g, " ").trim();
  if (!flat) return fallback;
  return truncate(flat, 280);
}

function buildBody(
  message: string,
  permalink: string,
  pageName: string,
): string {
  const text = message.trim();
  const footer = `\n\n---\n\nSource : [Publication Facebook — ${pageName}](${permalink})`;
  return text ? `${text}${footer}` : `Publication Facebook — ${pageName}.${footer}`;
}

async function findExistingFacebookArticle(
  permalink: string,
  storyId: string,
  title: string,
  publishedAt: string,
  authorLabel: string,
): Promise<boolean> {
  const supabase = getAdminSupabase();
  if (!supabase) return false;

  const ids = new Set<string>();
  if (storyId.length >= 8) ids.add(storyId);
  const fromLink =
    permalink.match(/\/posts\/(\d+)/)?.[1] ??
    permalink.match(/permalink\/(\d+)/)?.[1] ??
    permalink.match(/fbid=(\d+)/)?.[1];
  if (fromLink && fromLink.length >= 8) ids.add(fromLink);

  for (const id of ids) {
    const { data: byStory } = await supabase
      .from("articles")
      .select("id")
      .or(`slug.like.%-fb-${id},slug.like.%-fb-%-${id},body.ilike.%${id}%`)
      .limit(1);
    if (byStory?.length) return true;
  }

  const titleKey = normalizeTitleKey(title.slice(0, 160));
  if (titleKey.length >= 24) {
    const day = publishedAt.slice(0, 10);
    const nextDay = new Date(`${day}T00:00:00.000Z`);
    nextDay.setUTCDate(nextDay.getUTCDate() + 1);
    const { data: sameDay } = await supabase
      .from("articles")
      .select("id, title")
      .eq("author", authorLabel)
      .gte("published_at", `${day}T00:00:00.000Z`)
      .lt("published_at", nextDay.toISOString());
    for (const row of sameDay ?? []) {
      if (normalizeTitleKey(row.title.slice(0, 160)) === titleKey) {
        return true;
      }
    }

    // Coupure Te Ito Rau déjà republiée par MooreaNews (ou l’inverse).
    if (/info coupure|coupure d['']?[ée]lectricit/i.test(title)) {
      const since = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString();
      const { data: coupureRows } = await supabase
        .from("articles")
        .select("id, title")
        .gte("published_at", since)
        .or("title.ilike.%INFO COUPURE%,title.ilike.%COUPURE D%ÉLECTRICIT%,title.ilike.%COUPURE D%ELECTRICIT%")
        .limit(40);
      for (const row of coupureRows ?? []) {
        if (normalizeTitleKey(row.title.slice(0, 160)) === titleKey) {
          return true;
        }
      }
    }
  }

  return false;
}

function fallbackEventDate(createdTime?: string): string {
  if (createdTime) {
    const d = createdTime.slice(0, 10);
    if (d >= new Date().toISOString().slice(0, 10)) return d;
  }
  const next = new Date();
  next.setDate(next.getDate() + 7);
  return next.toISOString().slice(0, 10);
}

async function importAsEvent(
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
  published: boolean,
): Promise<{ ok: true; title: string; id: string; date: string } | { ok: false; reason: string }> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const permalink =
    post.permalink_url ??
    `${config.homepage.replace(/\/$/, "")}/posts/${post.id}`;
  const message = post.message?.trim() ?? "";

  const { data: existing } = await supabase
    .from("events")
    .select("id")
    .eq("url", permalink)
    .maybeSingle();

  if (existing) return { ok: false, reason: "duplicate" };

  const title = humanEventTitle(
    titleFromMessage(message, `${config.pageName} — événement`),
    `${config.pageName} — événement`,
  );
  const refDay = post.created_time?.slice(0, 10);
  const date =
    parseDateFromMessage(message, refDay) ?? fallbackEventDate(post.created_time);
  const today = new Date().toISOString().slice(0, 10);
  if (hasRelativeWeekdayDate(message) && date < today) {
    return { ok: false, reason: "past_relative_event" };
  }
  const startTime = parseTimeFromMessage(message);
  const district = parseDistrictFromMessage(message);
  const location = parseLocationFromMessage(message);
  const description = message || `Événement repéré sur ${config.pageName}.`;

  const { data, error } = await supabase
    .from("events")
    .insert({
      title,
      description: buildBody(description, permalink, config.pageName),
      category: eventCategoryFromMessage(message),
      date,
      start_time: startTime,
      location,
      district,
      organizer: config.pageName,
      cover_url: post.full_picture?.trim() || null,
      url: permalink,
      published,
    })
    .select("id")
    .single();

  if (error || !data) {
    return { ok: false, reason: error?.message ?? "insert failed" };
  }

  return { ok: true, title, id: data.id, date };
}

async function importAsAnnouncement(
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
  published: boolean,
): Promise<{ ok: true; title: string; id: string } | { ok: false; reason: string }> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const permalink =
    post.permalink_url ??
    `${config.homepage.replace(/\/$/, "")}/posts/${post.id}`;
  const message = post.message?.trim() ?? "";
  const marker = `fb-import:${post.id}`;

  const { data: existing } = await supabase
    .from("announcements")
    .select("id")
    .ilike("body", `%${marker}%`)
    .maybeSingle();

  if (existing) return { ok: false, reason: "duplicate" };

  const title = titleFromMessage(message, `${config.pageName} — annonce`);
  const body = `${buildBody(message || title, permalink, config.pageName)}\n\n${marker}`;

  const { data, error } = await supabase
    .from("announcements")
    .insert({
      title,
      body,
      category: announcementCategoryFromMessage(message),
      district: parseDistrictFromMessage(message),
      cover_url: post.full_picture?.trim() || null,
      author: config.authorLabel,
      contact: config.pageName,
      published,
    })
    .select("id")
    .single();

  if (error || !data) {
    return { ok: false, reason: error?.message ?? "insert failed" };
  }

  return { ok: true, title, id: data.id };
}

async function importAsArticle(
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
  published: boolean,
  publishedAt: string,
): Promise<
  | { ok: true; title: string; slug: string; coverWarning?: string }
  | { ok: false; reason: string }
> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const permalink = permalinkForPost(
    { id: post.id, permalink_url: post.permalink_url },
    config.graphPageId ?? "350029589936",
  );
  const message = post.message?.trim() ?? "";
  const slug = slugForPost(config.pageKey, post.id);

  if (await isSlugImportBlocked(slug)) {
    return { ok: false, reason: "blocked_by_admin" };
  }

  const { data: existing } = await supabase
    .from("articles")
    .select("id")
    .eq("slug", slug)
    .maybeSingle();

  if (existing) return { ok: false, reason: "duplicate" };

  const hasImage = Boolean(post.full_picture?.trim());
  const timeLabel = tahitiTimeLabel(publishedAt);
  const title = articleTitleFromPost(message, config, hasImage, publishedAt);

  const isDuplicate = await findExistingFacebookArticle(
    permalink,
    facebookStoryIdFromPostId(post.id),
    title,
    publishedAt,
    config.authorLabel,
  );
  if (isDuplicate) return { ok: false, reason: "duplicate" };

  const persist = await persistFacebookCoverForPost(
    { id: post.id, full_picture: post.full_picture, permalink_url: permalink },
    slug,
    config.graphPageId ?? "350029589936",
  );
  const cover = coverUrlForDatabase(persist);
  const excerpt =
    facebookExcerpt(message, `Publication Facebook ${config.pageName} · ${timeLabel}`);
  const body = buildBody(message, permalink, config.pageName);

  if (
    !config.importAllFeedPosts &&
    isEmptyFacebookArticleShell({
      title,
      excerpt,
      body,
      cover_url: cover,
    })
  ) {
    return { ok: false, reason: "empty_shell" };
  }

  if (
    config.importAllFeedPosts &&
    !message &&
    !post.full_picture?.trim() &&
    !cover
  ) {
    return { ok: false, reason: "meta_content_unavailable" };
  }

  const { data, error } = await supabase
    .from("articles")
    .insert({
      slug,
      title: title.slice(0, 500),
      excerpt,
      body,
      category: "actualites",
      tags: ["facebook-import", config.tag],
      cover_url: cover,
      author: config.authorLabel,
      featured: false,
      published,
      published_at: publishedAt,
    })
    .select("slug")
    .single();

  if (error || !data) return { ok: false, reason: error?.message ?? "insert failed" };
  await hideExternalArticlesForArticleSlug(slug);
  if (post.full_picture?.trim() && !cover) {
    return {
      ok: true,
      title,
      slug: data.slug,
      coverWarning: coverPersistUserMessage(data.slug, persist.reason),
    };
  }
  return { ok: true, title, slug: data.slug };
}

async function repairFacebookArticle(
  articleId: string,
  slug: string,
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
  publishedAt: string,
  existingCoverUrl?: string | null,
): Promise<
  | { ok: true; title: string; slug: string; coverWarning?: string }
  | { ok: false; reason: string }
> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const permalink = permalinkForPost(
    { id: post.id, permalink_url: post.permalink_url },
    config.graphPageId ?? "350029589936",
  );
  const message = post.message?.trim() ?? "";
  const hasImage = Boolean(post.full_picture?.trim());
  const title = articleTitleFromPost(message, config, hasImage, publishedAt);
  const timeLabel = tahitiTimeLabel(publishedAt);
  const persist = await persistFacebookCoverForPost(
    {
      id: post.id,
      full_picture: post.full_picture ?? existingCoverUrl,
      permalink_url: permalink,
    },
    slug,
    config.graphPageId ?? "350029589936",
  );
  const cover = coverUrlForDatabase(persist);

  const patch: {
    title: string;
    excerpt: string;
    body: string;
    updated_at: string;
    cover_url?: string | null;
  } = {
    title: title.slice(0, 500),
    excerpt: facebookExcerpt(
      message,
      `Publication Facebook ${config.pageName} · ${timeLabel}`,
    ),
    body: buildBody(message, permalink, config.pageName),
    updated_at: new Date().toISOString(),
  };
  if (cover) patch.cover_url = cover;
  else if (isFacebookCdnCoverUrl(existingCoverUrl)) patch.cover_url = null;

  const { error } = await supabase
    .from("articles")
    .update(patch)
    .eq("id", articleId);

  if (error) return { ok: false, reason: error.message };
  await hideExternalArticlesForArticleSlug(slug);
  if (
    (post.full_picture?.trim() || existingCoverUrl?.trim()) &&
    !cover
  ) {
    return {
      ok: true,
      title,
      slug,
      coverWarning: coverPersistUserMessage(slug, persist.reason),
    };
  }
  return { ok: true, title, slug };
}

/** Graph/OG + copie Supabase quand l’affiche manque en base. */
async function repairFacebookCoverFromGraph(
  articleId: string,
  slug: string,
  post: FacebookPostForImport,
  config: FacebookPageImportConfig,
): Promise<{ ok: true; slug: string } | { ok: false; reason: string }> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const enriched = await enrichPost(post, config);
  const remote = enriched.full_picture?.trim();
  const persist = remote
    ? await persistFacebookCoverForPost(
        {
          id: post.id,
          full_picture: remote,
          permalink_url: enriched.permalink_url,
        },
        slug,
        config.graphPageId ?? "350029589936",
      )
    : await persistFacebookCoverForPost(
        {
          id: post.id,
          full_picture: null,
          permalink_url: enriched.permalink_url ?? post.permalink_url,
        },
        slug,
        config.graphPageId ?? "350029589936",
      );
  const cover = coverUrlForDatabase(persist);
  if (!cover) {
    return { ok: false, reason: persist.reason };
  }

  const { error } = await supabase
    .from("articles")
    .update({
      cover_url: cover,
      updated_at: new Date().toISOString(),
    })
    .eq("id", articleId);

  if (error) return { ok: false, reason: error.message };
  await hideExternalArticlesForArticleSlug(slug);
  return { ok: true, slug };
}

function postIdFromMooreaNewsArticleSlug(slug: string): string | null {
  const m = slug.match(/^mooreanews-fb-(\d+)-(\d+)$/);
  if (!m) return null;
  return `${m[1]}_${m[2]}`;
}

/** Rattrape les coquilles vides en base (hors batch Graph du cron). */
async function repairPendingPlaceholderFacebookArticlesFromDb(
  config: FacebookPageImportConfig,
  limit: number,
): Promise<{
  repaired: number;
  failed: number;
  errors: string[];
  warnings: string[];
}> {
  const out = { repaired: 0, failed: 0, errors: [] as string[], warnings: [] as string[] };
  const supabase = getAdminSupabase();
  if (!supabase || !config.importAllFeedPosts) return out;

  const { data, error } = await supabase
    .from("articles")
    .select("id, slug, title, excerpt, body, cover_url, published_at")
    .like("slug", `${config.pageKey}-fb-%`)
    .order("published_at", { ascending: false })
    .limit(Math.min(limit * 4, 120));

  if (error) {
    out.errors.push(error.message);
    return out;
  }

  const token = config.pageAccessToken?.trim();
  let done = 0;

  for (const row of data ?? []) {
    if (done >= limit) break;
    const slug = row.slug ?? "";
    if (!slug || !isFacebookArticleNeedsRepair({ ...row, slug })) continue;

    const graphId = postIdFromMooreaNewsArticleSlug(slug);
    if (!graphId) continue;

    let post: FacebookPostForImport = {
      id: graphId,
      created_time: row.published_at ?? undefined,
    };

    if (token) {
      const detailed = await fetchGraphPostById(graphId, token);
      if (detailed) {
        post = {
          ...post,
          ...detailed,
          created_time: detailed.created_time ?? post.created_time,
        };
      }
      const fbid = graphId.split("_").pop() ?? "";
      const pageId = config.graphPageId ?? "350029589936";
      if (!post.message?.trim() && !post.full_picture?.trim() && fbid) {
        const { fetchGraphPhotoById, graphPostFromPhotoFbidFallback } =
          await import("@/lib/facebook-watch");
        const photo = await fetchGraphPhotoById(fbid, pageId, token);
        if (photo) {
          post = {
            ...post,
            id: photo.id,
            message: photo.message ?? post.message,
            full_picture: photo.full_picture ?? post.full_picture,
            permalink_url: photo.permalink_url ?? post.permalink_url,
            created_time: photo.created_time ?? post.created_time,
          };
        }
      }
      if (!post.message?.trim() && !post.full_picture?.trim() && fbid) {
        const { graphPostFromPhotoFbidFallback } = await import(
          "@/lib/facebook-watch"
        );
        const ogPost = await graphPostFromPhotoFbidFallback(fbid, pageId);
        if (ogPost) {
          post = {
            id: ogPost.id,
            message: ogPost.message,
            full_picture: ogPost.full_picture,
            permalink_url: ogPost.permalink_url,
            created_time: ogPost.created_time ?? post.created_time,
          };
        }
      }
    }

    post = {
      ...post,
      permalink_url: permalinkForPost(
        post,
        config.graphPageId ?? "350029589936",
      ),
    };
    post = await enrichPost(post, config);
    const freshness = shouldImportFacebookPost(
      post.message?.trim() ?? "",
      post.created_time,
      post,
      { importAllFeedPosts: true },
    );
    if (!freshness.ok) continue;

    const stillPlaceholder =
      !post.message?.trim() &&
      !post.full_picture?.trim();

    if (stillPlaceholder) {
      out.failed += 1;
      out.warnings.push(`${slug}: contenu Facebook toujours inaccessible`);
      continue;
    }

    const r = await repairFacebookArticle(
      row.id,
      slug,
      post,
      config,
      freshness.publishedAt,
      row.cover_url,
    );
    if (r.ok) {
      out.repaired += 1;
      done += 1;
      if ("coverWarning" in r && r.coverWarning) {
        out.warnings.push(r.coverWarning);
      }
    } else {
      out.failed += 1;
      out.warnings.push(`${slug}: ${r.reason}`);
    }
  }

  return out;
}

/** Recopie fbcdn → Supabase sans enrichissement Graph/OG (cron rapide). */
async function repairFacebookCoverOnly(
  articleId: string,
  slug: string,
  postId: string,
  existingCoverUrl: string,
): Promise<{ ok: true; slug: string } | { ok: false; reason: string }> {
  const supabase = getAdminSupabase();
  if (!supabase) return { ok: false, reason: "Supabase absent" };

  const persist = await persistFacebookCoverUrl(existingCoverUrl, postId);
  const cover = coverUrlForDatabase(persist);
  if (!cover) {
    return { ok: false, reason: persist.reason };
  }

  const { error } = await supabase
    .from("articles")
    .update({
      cover_url: cover,
      updated_at: new Date().toISOString(),
    })
    .eq("id", articleId);

  if (error) return { ok: false, reason: error.message };
  await hideExternalArticlesForArticleSlug(slug);
  return { ok: true, slug };
}

/** Route chaque post vers Événement / Annonce / Actualité. */
export async function importFacebookPostsAsContent(
  posts: FacebookPostForImport[],
  config: FacebookPageImportConfig,
): Promise<FacebookContentImportResult> {
  const result: FacebookContentImportResult = {
    eventsCreated: 0,
    announcementsCreated: 0,
    articlesCreated: 0,
    alertsCreated: 0,
    skipped: 0,
    skippedStale: 0,
    errors: [],
    createdEvents: [],
    createdArticles: [],
    repairedArticles: [],
    createdAnnouncements: [],
    createdAlerts: [],
    warnings: [],
  };

  if (!importEnabled(config)) return result;

  const published = isAutoImportFeedPage(config) ? true : publishedByDefault();

  type ExistingRow = {
    id: string;
    slug: string;
    title: string;
    excerpt: string | null;
    body: string;
    cover_url: string | null;
  };

  const existingBySlug = new Map<string, ExistingRow>();
  if (config.importAllFeedPosts) {
    const supabase = getAdminSupabase();
    if (supabase) {
      if (config.repairOnly) {
        const { data: repairRows } = await supabase
          .from("articles")
          .select("id, slug, title, excerpt, body, cover_url")
          .like("slug", "mooreanews-fb-%")
          .order("published_at", { ascending: false })
          .limit(80);
        for (const row of repairRows ?? []) {
          if (!row.slug) continue;
          if (isFacebookArticleNeedsRepair({ ...row, slug: row.slug })) {
            existingBySlug.set(row.slug, row);
          }
        }
      } else {
        const batchSlugs = posts.map((raw) => slugForPost(config.pageKey, raw.id));
        let query = supabase
          .from("articles")
          .select("id, slug, title, excerpt, body, cover_url");
        if (config.cronLight && batchSlugs.length > 0) {
          query = query.in("slug", batchSlugs);
        } else {
          query = query.like("slug", `${config.pageKey}-fb-%`);
        }
        const { data } = await query;
        for (const row of data ?? []) {
          if (row.slug) existingBySlug.set(row.slug, row);
        }
      }
    }
  }

  let repairsThisRun = 0;
  let coverPersistsThisRun = 0;
  const skipRepairs =
    config.skipRepairs === true ||
    (config.newPostsOnly === true && config.repairOnly !== true);
  const maxFullRepairs = config.cronLight
    ? 30
    : config.importAllFeedPosts
      ? facebookCronMaxRepairsPerRun()
      : posts.length;
  const maxCoverPersists = config.cronLight ? 30 : 50;

  const sortedPosts =
    config.cronLight && config.importAllFeedPosts
      ? [...posts].sort((a, b) => {
          const slugA = slugForPost(config.pageKey, a.id);
          const slugB = slugForPost(config.pageKey, b.id);
          const exA = existingBySlug.get(slugA);
          const exB = existingBySlug.get(slugB);
          const priA = !exA
            ? 2
            : isFacebookArticleNeedsRepair({ ...exA, slug: slugA })
              ? 0
              : 3;
          const priB = !exB
            ? 2
            : isFacebookArticleNeedsRepair({ ...exB, slug: slugB })
              ? 0
              : 3;
          return priA - priB;
        })
      : posts;

  let toProcess = sortedPosts;
  if (config.repairOnly) {
    const cap = Math.max(1, config.newPostsLimit ?? 1);
    const postsBySlug = new Map(
      sortedPosts.map((raw) => [slugForPost(config.pageKey, raw.id), raw]),
    );
    const repairSlugs = [...existingBySlug.keys()].slice(0, cap);
    const resolved: FacebookPostForImport[] = [];
    for (const slug of repairSlugs) {
      const fromBatch = postsBySlug.get(slug);
      if (fromBatch) {
        resolved.push(fromBatch);
        continue;
      }
      const graphId = graphPostIdFromMooreaNewsSlug(slug);
      if (graphId && config.pageAccessToken) {
        const fetched = await fetchGraphPostById(graphId, config.pageAccessToken);
        if (fetched) resolved.push(fetched);
      }
    }
    toProcess = resolved;
  } else if (config.newPostsOnly) {
    const cap = Math.max(1, config.newPostsLimit ?? 3);
    toProcess = sortedPosts
      .filter((raw) => !existingBySlug.has(slugForPost(config.pageKey, raw.id)))
      .slice(0, cap);
  }

  for (const raw of toProcess) {
    const slug = slugForPost(config.pageKey, raw.id);
    const filterOpts = config.importAllFeedPosts
      ? { importAllFeedPosts: true as const }
      : undefined;

    if (config.importAllFeedPosts && !isRecentFacebookPost(raw.created_time)) {
      result.skippedStale += 1;
      continue;
    }

    if (config.importAllFeedPosts) {
      const existing = existingBySlug.get(slug);

      if (
        !skipRepairs &&
        existing &&
        !isFacebookArticleNeedsRepair({ ...existing, slug })
      ) {
        if (
          isFacebookCoverMissingRepair({ ...existing, slug }) &&
          coverPersistsThisRun < maxCoverPersists
        ) {
          const r = await repairFacebookCoverFromGraph(
            existing.id,
            slug,
            raw,
            config,
          );
          if (r.ok) {
            result.articlesRepaired = (result.articlesRepaired ?? 0) + 1;
            result.coversPersisted = (result.coversPersisted ?? 0) + 1;
            coverPersistsThisRun += 1;
          } else if (r.reason !== "missing_url") {
            result.coversFailed = (result.coversFailed ?? 0) + 1;
            result.warnings.push(coverPersistUserMessage(slug, r.reason));
          }
        }
        result.skipped += 1;
        continue;
      }

      if (
        !skipRepairs &&
        existing &&
        isFacebookArticleNeedsRepair({ ...existing, slug })
      ) {
        if (isFacebookCoverNeedsPersistOnly({ ...existing, slug })) {
          if (coverPersistsThisRun >= maxCoverPersists) {
            result.skipped += 1;
            continue;
          }
          const r = await repairFacebookCoverOnly(
            existing.id,
            slug,
            raw.id,
            existing.cover_url ?? "",
          );
          if (r.ok) {
            result.articlesRepaired = (result.articlesRepaired ?? 0) + 1;
            result.coversPersisted = (result.coversPersisted ?? 0) + 1;
            pushRepairedArticleNotice(
              result,
              existing.title,
              r.slug,
              existing.excerpt,
              existing.body,
            );
            coverPersistsThisRun += 1;
          } else {
            result.coversFailed = (result.coversFailed ?? 0) + 1;
            result.warnings.push(
              coverPersistUserMessage(slug, r.reason),
            );
          }
          continue;
        }

        if (repairsThisRun >= maxFullRepairs) {
          result.skipped += 1;
          continue;
        }
        const post = await enrichPost(raw, config);
        const freshness = shouldImportFacebookPost(
          post.message?.trim() ?? "",
          post.created_time,
          post,
          filterOpts,
        );
        if (!freshness.ok) {
          result.skippedStale += 1;
          continue;
        }
        const r = await repairFacebookArticle(
          existing.id,
          slug,
          post,
          config,
          freshness.publishedAt,
          existing.cover_url,
        );
        if (r.ok) {
          result.articlesRepaired = (result.articlesRepaired ?? 0) + 1;
          pushRepairedArticleNotice(result, r.title, r.slug);
          if ("coverWarning" in r && r.coverWarning) {
            result.warnings.push(r.coverWarning);
            result.coversFailed = (result.coversFailed ?? 0) + 1;
          } else if (post.full_picture?.trim()) {
            result.coversPersisted = (result.coversPersisted ?? 0) + 1;
          }
          repairsThisRun += 1;
        } else {
          pushImportFailure(result, `repair ${post.id}`, r.reason);
        }
        continue;
      }
    }

    const post = await enrichPost(raw, config);
    const message = post.message?.trim() ?? "";
    const freshness = shouldImportFacebookPost(
      message,
      post.created_time,
      post,
      filterOpts,
    );
    if (!freshness.ok) {
      result.skippedStale += 1;
      continue;
    }

    if (config.importAllFeedPosts) {
      const r = await importAsArticle(
        post,
        config,
        published,
        freshness.publishedAt,
      );
      if (r.ok) {
        result.articlesCreated += 1;
        const notice = articleTelegramNotice(r.title, r.slug);
        if (notice) result.createdArticles.push(notice);
        if ("coverWarning" in r && r.coverWarning) {
          result.warnings.push(r.coverWarning);
          result.coversFailed = (result.coversFailed ?? 0) + 1;
        } else if (post.full_picture?.trim()) {
          result.coversPersisted = (result.coversPersisted ?? 0) + 1;
        }
      } else if (r.reason === "duplicate" || r.reason === "empty_shell") {
        result.skipped += 1;
      } else {
        pushImportFailure(result, `article ${post.id}`, r.reason);
      }
      continue;
    }

    const hasImage = Boolean(post.full_picture?.trim());
    const target = routeFacebookImport(message, {
      sourceLabel: config.pageName,
      hasImage,
      importAllFeedPosts: config.importAllFeedPosts,
    });

    if (target === "skip") {
      result.skippedStale += 1;
      continue;
    }

    if (target === "meteo_alert") {
      const alert = await tryImportFacebookMeteoAlert({
        message,
        permalink: post.permalink_url,
        imageUrl: post.full_picture,
        sourceLabel: config.pageName,
        fallbackTitle: `${config.pageName} — vigilance météo`,
      });
      if (alert.created && alert.title) {
        result.alertsCreated += 1;
        result.createdAlerts.push(alert.title);
        continue;
      }
    }

    if (target === "ferry_alert" && config.allowFerryAlerts !== false) {
      const alert = await tryImportFacebookAlert({
        message,
        permalink: post.permalink_url,
        imageUrl: post.full_picture,
        fallbackTitle: `${config.pageName} — info ferry`,
      });
      if (alert.created && alert.title) {
        result.alertsCreated += 1;
        result.createdAlerts.push(alert.title);
        continue;
      }
    }

    if (target === "event") {
      const r = await importAsEvent(post, config, eventsPublishedByDefault());
      if (r.ok) {
        result.eventsCreated += 1;
        result.createdEvents.push({
          title: r.title,
          id: r.id,
          date: r.date,
        });
      } else if (r.reason === "duplicate" || r.reason === "empty_shell") {
        result.skipped += 1;
      } else {
        pushImportFailure(result, `event ${post.id}`, r.reason);
      }
      continue;
    }

    if (target === "announcement") {
      const r = await importAsAnnouncement(post, config, published);
      if (r.ok) {
        result.announcementsCreated += 1;
        result.createdAnnouncements.push({ title: r.title, id: r.id });
      } else if (r.reason === "duplicate" || r.reason === "empty_shell") {
        result.skipped += 1;
      } else {
        pushImportFailure(result, `announcement ${post.id}`, r.reason);
      }
      continue;
    }

    const r = await importAsArticle(post, config, published, freshness.publishedAt);
    if (r.ok) {
      result.articlesCreated += 1;
      const notice = articleTelegramNotice(r.title, r.slug);
      if (notice) result.createdArticles.push(notice);
      if ("coverWarning" in r && r.coverWarning) {
        result.warnings.push(r.coverWarning);
        result.coversFailed = (result.coversFailed ?? 0) + 1;
      } else if (post.full_picture?.trim()) {
        result.coversPersisted = (result.coversPersisted ?? 0) + 1;
      }
    } else if (r.reason === "duplicate") {
      result.skipped += 1;
    } else {
      pushImportFailure(result, `article ${post.id}`, r.reason);
    }
  }

  if (config.importAllFeedPosts) {
    const shellLimit = config.cronLight
      ? Math.min(facebookCronMaxRepairsPerRun(), 25)
      : facebookCronMaxRepairsPerRun();
    const shells = await repairPendingPlaceholderFacebookArticlesFromDb(
      config,
      shellLimit,
    );
    result.articlesRepaired =
      (result.articlesRepaired ?? 0) + shells.repaired;
    result.warnings.push(...shells.warnings);
    result.errors.push(...shells.errors);
    if (shells.failed > 0) {
      result.coversFailed = (result.coversFailed ?? 0) + shells.failed;
    }
    const hidden = await unpublishEmptyFacebookShells();
    if (hidden > 0) {
      result.warnings.push(
        `${hidden} coquille(s) Facebook dépubliée(s) (sans contenu récupérable)`,
      );
    }
  }

  if (config.cronLight && config.importAllFeedPosts) {
    const queue = await repairPendingFbcdnCoversFromDb(maxCoverPersists);
    result.articlesRepaired =
      (result.articlesRepaired ?? 0) + queue.repaired;
    result.coversPersisted =
      (result.coversPersisted ?? 0) + queue.repaired;
    result.coversFailed = (result.coversFailed ?? 0) + queue.failed;
    result.warnings.push(...queue.warnings);
    result.errors.push(...queue.errors);
  }

  return result;
}

const MOOREANEWS_IMPORT_CONFIG = (): FacebookPageImportConfig => ({
  pageKey: "mooreanews",
  pageName: "MooreaNews",
  homepage: "https://www.facebook.com/MooreaNews",
  authorLabel: "MooreaNews (Facebook)",
  tag: "moorea-news-fb",
  allowFerryAlerts: true,
  importAllFeedPosts: true,
  graphPageId: "350029589936",
});

/** Réintègre à l’identique des posts MooreaNews par fbid (texte + affiche + lien). */
export async function forceRepairMooreaNewsByFbid(fbids: string[]): Promise<{
  ok: boolean;
  results: Array<{
    fbid: string;
    slug: string;
    ok: boolean;
    title?: string;
    hasText: boolean;
    hasCover: boolean;
    permalink?: string;
    reason?: string;
  }>;
}> {
  const { getMooreaNewsPageAccessToken, fetchMooreaNewsPostByFbid } =
    await import("@/lib/facebook-watch");
  const token = await getMooreaNewsPageAccessToken();
  const supabase = getAdminSupabase();
  const results: Array<{
    fbid: string;
    slug: string;
    ok: boolean;
    title?: string;
    hasText: boolean;
    hasCover: boolean;
    permalink?: string;
    reason?: string;
  }> = [];

  if (!token || !supabase) {
    return {
      ok: false,
      results: fbids.map((fbid) => ({
        fbid,
        slug: `mooreanews-fb-350029589936-${fbid}`,
        ok: false,
        hasText: false,
        hasCover: false,
        reason: !token ? "token_facebook_absent" : "supabase_absent",
      })),
    };
  }

  const config: FacebookPageImportConfig = {
    ...MOOREANEWS_IMPORT_CONFIG(),
    pageAccessToken: token,
  };

  for (const fbid of fbids) {
    const slug = `mooreanews-fb-350029589936-${fbid}`;
    const post = await fetchMooreaNewsPostByFbid(fbid, token);
    const permalink = `https://www.facebook.com/MooreaNews/posts/${fbid}`;

    const { data: existing } = await supabase
      .from("articles")
      .select("id, cover_url")
      .eq("slug", slug)
      .maybeSingle();

    if (!post) {
      if (existing?.id) {
        await supabase.from("articles").delete().eq("id", existing.id);
        await hideExternalArticlesForArticleSlug(slug);
      }
      results.push({
        fbid,
        slug,
        ok: false,
        hasText: false,
        hasCover: false,
        permalink,
        reason: "meta_api_contenu_indisponible",
      });
      continue;
    }

    const message = post.message?.trim() ?? "";
    const hasCover = Boolean(post.full_picture?.trim());

    if (!message && !hasCover) {
      if (existing?.id) {
        await supabase.from("articles").delete().eq("id", existing.id);
        await hideExternalArticlesForArticleSlug(slug);
      }
      results.push({
        fbid,
        slug,
        ok: false,
        hasText: false,
        hasCover: false,
        permalink,
        reason: "meta_api_contenu_indisponible",
      });
      continue;
    }

    const freshness = shouldImportFacebookPost(
      message,
      post.created_time,
      post,
      { importAllFeedPosts: true },
    );
    if (!freshness.ok) {
      results.push({
        fbid,
        slug,
        ok: false,
        hasText: Boolean(message),
        hasCover: hasCover,
        permalink,
        reason: freshness.reason,
      });
      continue;
    }

    if (existing?.id) {
      const r = await repairFacebookArticle(
        existing.id,
        slug,
        post,
        config,
        freshness.publishedAt,
        existing.cover_url,
      );
      results.push({
        fbid,
        slug,
        ok: r.ok,
        title: r.ok ? r.title : undefined,
        hasText: message.length > 0,
        hasCover: Boolean(post.full_picture?.trim()),
        permalink,
        reason: r.ok ? undefined : r.reason,
      });
      continue;
    }

    const r = await importAsArticle(post, config, true, freshness.publishedAt);
    results.push({
      fbid,
      slug,
      ok: r.ok,
      title: r.ok ? r.title : undefined,
      hasText: message.length > 0,
      hasCover: Boolean(post.full_picture?.trim()),
      permalink,
      reason: r.ok ? undefined : r.reason,
    });
  }

  return { ok: results.every((r) => r.ok), results };
}
