/**
 * Suppression des imports Facebook obsolètes ou vides (cron + admin).
 */

import { isStaleFacebookImportRow, isFacebookAutoGeneratedPlaceholder, isFacebookArticleCompleteOnSite } from "@/lib/facebook-import-filters";
import { isFacebookCdnCoverUrl } from "@/lib/facebook-cover-persist";
import { isStaleFacebookEvent } from "@/lib/facebook-event-filters";
import { getAdminSupabase } from "@/lib/supabase/admin";

async function hideExternalArticlesForArticleSlug(slug: string): Promise<void> {
  const admin = getAdminSupabase();
  if (!admin) return;
  await admin
    .from("external_articles")
    .update({ hidden: true })
    .ilike("external_id", `%${slug}%`);
}

/** Supprime les fiches Facebook trop vieilles, vides ou sans année détectable dans le texte. */
export async function purgeStaleFacebookImports(): Promise<{
  deleted: number;
}> {
  const admin = getAdminSupabase();
  if (!admin) return { deleted: 0 };

  const { data: tagged } = await admin
    .from("articles")
    .select("id, slug, title, excerpt, body, tags, published_at, cover_url")
    .filter("tags", "cs", "{facebook-import}");

  const { data: bySlug } = await admin
    .from("articles")
    .select("id, slug, title, excerpt, body, tags, published_at, cover_url")
    .ilike("slug", "%-fb-%");

  const seen = new Set<string>();
  const rows = [...(tagged ?? []), ...(bySlug ?? [])].filter((row) => {
    if (seen.has(row.id)) return false;
    seen.add(row.id);
    return true;
  });

  let deleted = 0;
  for (const row of rows ?? []) {
    if (!isStaleFacebookImportRow(row)) continue;
    if (row.slug) await hideExternalArticlesForArticleSlug(row.slug);
    const { error } = await admin.from("articles").delete().eq("id", row.id);
    if (!error) deleted += 1;
  }

  return { deleted };
}

/** Dépublie ou supprime les événements Facebook avec date recalée (ex. post 2022 → vendredi 2026). */
export async function purgeStaleFacebookEvents(): Promise<{
  unpublished: number;
  deleted: number;
}> {
  const admin = getAdminSupabase();
  if (!admin) return { unpublished: 0, deleted: 0 };

  const { data: rows } = await admin
    .from("events")
    .select("id, title, description, date, url, published, created_at")
    .ilike("url", "%facebook.com%");

  let unpublished = 0;
  let deleted = 0;

  for (const row of rows ?? []) {
    if (!isStaleFacebookEvent(row)) continue;

    if (row.published) {
      const { error } = await admin
        .from("events")
        .update({ published: false })
        .eq("id", row.id);
      if (!error) unpublished += 1;
      continue;
    }

    const { error } = await admin.from("events").delete().eq("id", row.id);
    if (!error) deleted += 1;
  }

  return { unpublished, deleted };
}

export async function countStaleFacebookEvents(): Promise<number> {
  const admin = getAdminSupabase();
  if (!admin) return 0;

  const { data: rows } = await admin
    .from("events")
    .select("id, title, description, date, url, published, created_at")
    .eq("published", true)
    .ilike("url", "%facebook.com%");

  return (rows ?? []).filter((row) => isStaleFacebookEvent(row)).length;
}

/** Nombre d’imports Facebook à nettoyer (admin). */
export async function countStaleFacebookImports(): Promise<number> {
  const admin = getAdminSupabase();
  if (!admin) return 0;

  const { data: tagged } = await admin
    .from("articles")
    .select("id, slug, title, excerpt, body, tags, published_at, cover_url")
    .filter("tags", "cs", "{facebook-import}");

  const { data: bySlug } = await admin
    .from("articles")
    .select("id, slug, title, excerpt, body, tags, published_at, cover_url")
    .ilike("slug", "%-fb-%");

  const seen = new Set<string>();
  let count = 0;
  for (const row of [...(tagged ?? []), ...(bySlug ?? [])]) {
    if (seen.has(row.id)) continue;
    seen.add(row.id);
    if (isStaleFacebookImportRow(row)) count += 1;
  }
  return count;
}

/** Dépublie les coquilles Facebook sans texte ni affiche Supabase. */
export async function unpublishEmptyFacebookShells(): Promise<number> {
  const admin = getAdminSupabase();
  if (!admin) return 0;

  const { data: rows } = await admin
    .from("articles")
    .select("id, slug, title, excerpt, body, cover_url, published")
    .eq("published", true)
    .like("slug", "mooreanews-fb-%");

  let unpublished = 0;
  for (const row of rows ?? []) {
    if (
      !isFacebookAutoGeneratedPlaceholder({
        title: row.title,
        excerpt: row.excerpt,
        body: row.body,
      })
    ) {
      continue;
    }
    if (
      isFacebookArticleCompleteOnSite({
        title: row.title,
        excerpt: row.excerpt,
        body: row.body,
        cover_url: row.cover_url,
        slug: row.slug,
      })
    ) {
      continue;
    }
    const cover = row.cover_url?.trim() ?? "";
    if (
      cover &&
      !isFacebookCdnCoverUrl(cover) &&
      cover.startsWith("http")
    ) {
      continue;
    }
    const { error } = await admin
      .from("articles")
      .update({ published: false, updated_at: new Date().toISOString() })
      .eq("id", row.id);
    if (!error) {
      if (row.slug) await hideExternalArticlesForArticleSlug(row.slug);
      unpublished += 1;
    }
  }
  return unpublished;
}
